export type Grade = "A" | "B" | "C" | "D";

export interface SkillEntry {
  id: string;
  name: string;
  repo: string;
  url: string;
  stars: string;
  category: string;
  summary: string;
  signal: string;
  platforms: string[];
  score: number;
  safety: Grade;
  docs: Grade;
  portability: Grade;
  badges: string[];
  risks: string[];
}

export const skills: SkillEntry[] = [
  {
    id: "superpowers",
    name: "Superpowers",
    repo: "obra/superpowers",
    url: "https://github.com/obra/superpowers",
    stars: "245k",
    category: "Workflow",
    summary: "Agentic skills framework and software-development methodology.",
    signal: "Methodology as skills",
    platforms: ["Claude", "Codex", "Cursor", "OpenCode"],
    score: 84,
    safety: "B",
    docs: "A",
    portability: "A",
    badges: ["Methodology", "Shell review", "Multi-platform"],
    risks: ["Review installer behavior and local file changes"]
  },
  {
    id: "graphify",
    name: "Graphify",
    repo: "Graphify-Labs/graphify",
    url: "https://github.com/Graphify-Labs/graphify",
    stars: "77k",
    category: "Engineering",
    summary: "Builds a queryable knowledge graph from code, schemas, docs, and media.",
    signal: "Repo context engine",
    platforms: ["Claude", "Codex", "Cursor", "Gemini", "OpenCode"],
    score: 81,
    safety: "B",
    docs: "A",
    portability: "A",
    badges: ["Knowledge graph", "Local index", "Dependency review"],
    risks: ["Check indexing footprint, parser dependencies, and data retention"]
  },
  {
    id: "agent-skills",
    name: "Agent Skills",
    repo: "addyosmani/agent-skills",
    url: "https://github.com/addyosmani/agent-skills",
    stars: "68k",
    category: "Engineering",
    summary: "Production-grade engineering skills for coding agents.",
    signal: "Practical engineering playbooks",
    platforms: ["Claude", "Cursor"],
    score: 86,
    safety: "B",
    docs: "A",
    portability: "B",
    badges: ["Engineering", "Examples", "Review scripts"],
    risks: ["May include executable workflows"]
  },
  {
    id: "taste-skill",
    name: "Taste Skill",
    repo: "Leonxlnx/taste-skill",
    url: "https://github.com/Leonxlnx/taste-skill",
    stars: "55k",
    category: "Design",
    summary: "A focused skill for improving AI design taste and reducing generic output.",
    signal: "Memorable, narrow promise",
    platforms: ["Claude", "Codex"],
    score: 83,
    safety: "B",
    docs: "B",
    portability: "B",
    badges: ["Frontend", "Taste rules", "Example quality"],
    risks: ["Needs evidence that guidance improves outputs across models"]
  },
  {
    id: "last30days-skill",
    name: "Last 30 Days Skill",
    repo: "mvanhorn/last30days-skill",
    url: "https://github.com/mvanhorn/last30days-skill",
    stars: "48k",
    category: "Research",
    summary: "Recency research across social, prediction, video, HN, and the web.",
    signal: "Freshness-aware research",
    platforms: ["Claude", "OpenClaw"],
    score: 76,
    safety: "B",
    docs: "B",
    portability: "B",
    badges: ["Web sources", "API review", "Attribution"],
    risks: ["Check external calls, API keys, rate limits, and citations"]
  },
  {
    id: "obsidian-skills",
    name: "Obsidian Skills",
    repo: "kepano/obsidian-skills",
    url: "https://github.com/kepano/obsidian-skills",
    stars: "39k",
    category: "Knowledge",
    summary: "Teaches agents to use Obsidian CLI and open Markdown/Canvas formats.",
    signal: "Local knowledge workflows",
    platforms: ["Claude", "Codex", "OpenCode"],
    score: 88,
    safety: "A",
    docs: "B",
    portability: "A",
    badges: ["Markdown", "Local files", "Vault review"],
    risks: ["Review vault write behavior and permission boundaries"]
  },
  {
    id: "marketing-skills",
    name: "Marketing Skills",
    repo: "coreyhaines31/marketingskills",
    url: "https://github.com/coreyhaines31/marketingskills",
    stars: "36k",
    category: "Marketing",
    summary: "CRO, copywriting, SEO, analytics, and growth engineering skills.",
    signal: "Go-to-market workflows",
    platforms: ["Claude", "Codex"],
    score: 82,
    safety: "B",
    docs: "A",
    portability: "B",
    badges: ["Growth", "Analytics", "Credential review"],
    risks: ["Check analytics/API credentials and source assumptions"]
  },
  {
    id: "openmontage",
    name: "OpenMontage",
    repo: "calesthio/OpenMontage",
    url: "https://github.com/calesthio/OpenMontage",
    stars: "32k",
    category: "Media",
    summary: "Agentic video-production system with pipelines, tools, and skills.",
    signal: "End-to-end creative pipeline",
    platforms: ["Claude", "Cursor", "Copilot"],
    score: 70,
    safety: "C",
    docs: "B",
    portability: "B",
    badges: ["Media APIs", "Heavy deps", "License review"],
    risks: ["Review AGPL terms, ffmpeg/assets, paid APIs, and generation costs"]
  },
  {
    id: "scientific-agent-skills",
    name: "Scientific Agent Skills",
    repo: "K-Dense-AI/scientific-agent-skills",
    url: "https://github.com/K-Dense-AI/scientific-agent-skills",
    stars: "30k",
    category: "Science",
    summary: "Research skills for biology, chemistry, medicine, and drug discovery.",
    signal: "Domain evidence matters",
    platforms: ["Claude", "Codex", "Cursor"],
    score: 79,
    safety: "B",
    docs: "B",
    portability: "A",
    badges: ["Research", "Database links", "Citation review"],
    risks: ["Verify database provenance, citations, and domain disclaimers"]
  },
  {
    id: "planning-with-files",
    name: "Planning With Files",
    repo: "OthmanAdi/planning-with-files",
    url: "https://github.com/OthmanAdi/planning-with-files",
    stars: "24k",
    category: "Workflow",
    summary: "Persistent Markdown plans for long-running agent tasks.",
    signal: "Crash-proof planning",
    platforms: ["Claude", "Codex", "Cursor", "OpenCode"],
    score: 85,
    safety: "B",
    docs: "A",
    portability: "A",
    badges: ["File writes", "Long-running", "Completion gates"],
    risks: ["Review plan file scope and deterministic completion gates"]
  },
  {
    id: "cybersecurity-skills",
    name: "Cybersecurity Skills",
    repo: "mukul975/Anthropic-Cybersecurity-Skills",
    url: "https://github.com/mukul975/Anthropic-Cybersecurity-Skills",
    stars: "24k",
    category: "Security",
    summary: "Cybersecurity skill set mapped to MITRE and NIST-style frameworks.",
    signal: "Dual-use discipline",
    platforms: ["Claude", "Codex", "Cursor", "Copilot", "Gemini"],
    score: 68,
    safety: "C",
    docs: "A",
    portability: "A",
    badges: ["Dual-use", "Framework mapped", "Authorization review"],
    risks: ["Needs safe-lab assumptions and dangerous-command checks"]
  },
  {
    id: "pm-skills",
    name: "PM Skills Marketplace",
    repo: "phuryn/pm-skills",
    url: "https://github.com/phuryn/pm-skills",
    stars: "22k",
    category: "Product",
    summary: "Product management skills spanning discovery, strategy, execution, and launch.",
    signal: "Structured PM outputs",
    platforms: ["Claude", "Codex"],
    score: 87,
    safety: "A",
    docs: "A",
    portability: "B",
    badges: ["Domain-specific", "Reusable templates", "No execution detected"],
    risks: ["Some outputs require human validation"]
  },
  {
    id: "claude-skills",
    name: "Claude Skills",
    repo: "alirezarezvani/claude-skills",
    url: "https://github.com/alirezarezvani/claude-skills",
    stars: "19k",
    category: "Marketplace",
    summary: "Broad multi-domain library with agents, commands, scripts, and plugins.",
    signal: "Marketplace stress test",
    platforms: ["Claude", "Codex", "Cursor", "Gemini"],
    score: 72,
    safety: "C",
    docs: "B",
    portability: "A",
    badges: ["Installer", "Scripts", "License review"],
    risks: ["Check installer behavior, duplicate names, scripts, and per-skill licenses"]
  },
  {
    id: "context-mode",
    name: "Context Mode",
    repo: "mksglu/context-mode",
    url: "https://github.com/mksglu/context-mode",
    stars: "18k",
    category: "Context",
    summary: "Context-window optimization with memory, routing, MCP, and hooks.",
    signal: "Token and memory control",
    platforms: ["Claude", "Codex", "Cursor", "Copilot", "OpenCode"],
    score: 74,
    safety: "B",
    docs: "B",
    portability: "A",
    badges: ["Hooks", "MCP", "Persistence"],
    risks: ["Review hook permissions, persistence paths, and sandboxing claims"]
  },
  {
    id: "notebooklm-py",
    name: "NotebookLM Py",
    repo: "teng-lin/notebooklm-py",
    url: "https://github.com/teng-lin/notebooklm-py",
    stars: "17k",
    category: "Research",
    summary: "Unofficial NotebookLM API, CLI, and agentic skill surface.",
    signal: "Unofficial API wrapper",
    platforms: ["Claude", "Codex", "OpenClaw"],
    score: 71,
    safety: "C",
    docs: "B",
    portability: "B",
    badges: ["Unofficial API", "Auth review", "CLI"],
    risks: ["Check account risk, auth handling, and data export behavior"]
  },
  {
    id: "gsap-skills",
    name: "GSAP Skills",
    repo: "greensock/gsap-skills",
    url: "https://github.com/greensock/gsap-skills",
    stars: "10k",
    category: "Frontend",
    summary: "Official skills for using GSAP animation patterns and plugins correctly.",
    signal: "Vendor-authored skill",
    platforms: ["Claude", "Cursor", "Codex"],
    score: 91,
    safety: "A",
    docs: "A",
    portability: "A",
    badges: ["Official", "Frontend", "Examples"],
    risks: ["Keep API guidance aligned with GSAP versions"]
  },
  {
    id: "claude-seo",
    name: "Claude SEO",
    repo: "AgriciDaniel/claude-seo",
    url: "https://github.com/AgriciDaniel/claude-seo",
    stars: "10k",
    category: "Marketing",
    summary: "SEO suite with sub-skills, sub-agents, reports, and optional services.",
    signal: "SEO operating system",
    platforms: ["Claude"],
    score: 73,
    safety: "C",
    docs: "B",
    portability: "C",
    badges: ["SEO", "Paid APIs", "Reports"],
    risks: ["Review Google/DataForSEO/Firecrawl credentials and source freshness"]
  },
  {
    id: "cc-sdd",
    name: "CC SDD",
    repo: "gotalab/cc-sdd",
    url: "https://github.com/gotalab/cc-sdd",
    stars: "3.5k",
    category: "Workflow",
    summary: "Spec-driven development harness for autonomous implementation.",
    signal: "Approved spec to code",
    platforms: ["Claude", "Codex", "Cursor", "Copilot", "Gemini", "OpenCode"],
    score: 84,
    safety: "B",
    docs: "A",
    portability: "A",
    badges: ["SDD", "Traceability", "Multi-platform"],
    risks: ["Check whether generated tasks remain tied to approved specs"]
  },
  {
    id: "hallmark",
    name: "Hallmark",
    repo: "Nutlope/hallmark",
    url: "https://github.com/Nutlope/hallmark",
    stars: "3.5k",
    category: "Design",
    summary: "Anti-slop design skill for Claude Code, Cursor, and Codex.",
    signal: "Taste guardrails",
    platforms: ["Claude", "Codex", "Cursor"],
    score: 89,
    safety: "A",
    docs: "B",
    portability: "A",
    badges: ["Design", "No exec", "Portable"],
    risks: ["Needs examples to prove design improvement across tasks"]
  },
  {
    id: "awesome-agent-skills",
    name: "Awesome Agent Skills",
    repo: "VoltAgent/awesome-agent-skills",
    url: "https://github.com/VoltAgent/awesome-agent-skills",
    stars: "27k",
    category: "Directory",
    summary: "Multi-platform directory for Claude Code, Codex, Gemini CLI, and Cursor.",
    signal: "Discovery benchmark",
    platforms: ["Claude", "Codex", "Cursor", "Gemini"],
    score: 88,
    safety: "A",
    docs: "A",
    portability: "A",
    badges: ["Curated list", "Multi-platform", "No execution detected"],
    risks: ["Quality varies across linked projects"]
  }
];

export const categories = ["All", ...Array.from(new Set(skills.map((skill) => skill.category)))];
